### ISSUE TITLE
  Explore how we use the pigpio lib 

### ISSUE THREAD

**Issue by jsduenass** [cychitivav/pai#28]
While reading through the documentation of the [pigpio lib](https://abyz.me.uk/rpi/pigpio/python.html#pigpio.pi) it states that: 
> the pigpio Python module can run on Windows, Macs, or Linux
and that it can be used to [connect to remotely to a raspberry](https://abyz.me.uk/rpi/pigpio/python.html#pi)

It would be interesting explore this option to facilitate testing code.

**Comment by cychitivav** [comment]
Thanks for your suggestion, I have created a version with that in PR #29
