### ISSUE TITLE
Bug: Docker launch sim

### ISSUE THREAD

**Issue by jsduenass** [cychitivav/pai#30]
when running `roslaunch pai sim.launch` in the Docker the launch fail

```
[ERROR] [1686156460.241993689, 1.435000000]: Exception thrown while initializing controller 'right_front_ctrl'.
Could not find resource 'right_front_joint' in 'hardware_interface::VelocityJointInterface'.
```

I thought it might be related with missing ROS depedencies in however even after installing all the dependencies in https://github.com/cychitivav/pai/blob/951ca9c63c6fe73660dc87310d84bdb785153710/Dockerfile. The problem still persisted.

**Comment by cychitivav** [comment]
Could you please write the whole output log?

**Comment by cychitivav** [comment]
I think I found the errors. It is because joint names are defined as `<left/right>_<back/front>` in the urdf and in config/controller.yaml are defined as `<back/front>_<left/right>`.
