### ISSUE TITLE
Motor fail case

### ISSUE THREAD

**Issue by jsduenass** [cychitivav/pai#38]
When testing the drivers with the motors. A fail case scenario was found when running in reverse and then changing the speed to zero.

We think this might be do to inside the implementation it does the change of direction before the change of speed so when running at -50  and then send the 0 speed. It transitions from -50 to 50 to 0. 

I think it would be a good idea to create a protection mechanism to avoid this fail case.

**Comment by cychitivav** [comment]
Turns out the motors draw a higher (16 A max) current that the one estimated. So, we had to change these drivers for ones with a higher max current (BTS7960).

![image](https://github.com/cychitivav/pai/assets/30636259/c51bcc00-5065-4c77-8222-a4531597630c)
