### ISSUE TITLE
Initialize all GPIO pins in LOW

### ISSUE THREAD

**Issue by cychitivav** [cychitivav/pai#40]
I tested the code on the raspberry and found that when I don't set all the GPIO pins to LOW, the code fails. 

When I put the motors in reverse, it sends both signals(forward and reverse) and measuring with the multimeter, I found that there is a 0.5 volt offset that is only eliminated by setting all the pins to LOW.

In conclusion, we need to find a way to start `pigpiod` automatically and set this GPIO pins to LOW.

**Comment by jsduenass** [comment]
This issue was caused by an error in the electronic connections.
